// FastTail -- Ultra-fast multi-stream log monitor and tail viewer.
// Copyright (c) Matteo Baccan -- https://github.com/matteobaccan/FastTail
// SPDX-License-Identifier: MIT

pub mod actions;
pub mod ansi;
pub mod audio;
pub mod auto_highlight;
pub mod baretail_bridge;
pub mod bookmark_report;
pub mod cli;
pub mod collapse;
pub mod color;
pub mod compare;
pub mod compressed;
pub mod config;
pub mod context_lines;
pub mod crash_handler;
pub mod dock_layout;
pub mod external_tools;
pub mod fields;
pub mod file_source;
pub mod filter_preset;
pub mod filter_tab;
pub mod find_all;
pub mod global_filter;
pub mod handoff;
pub mod html_converter;
pub mod i18n;
pub mod i18n_tui;
pub mod json_tree;
pub mod lock;
pub mod log_level;
pub mod paths;
pub mod print_mode;
pub mod renderer;
pub mod scan_job;
#[cfg(feature = "gui")]
pub mod screensaver;
pub mod session;
pub mod settings_model;
pub mod spool;
pub mod stdin_source;
pub mod tail_engine;
pub mod theme;
pub mod time_histogram;
pub mod time_range_text;
pub mod timestamp;
#[cfg(feature = "gui")]
pub mod tray;
#[cfg(feature = "tui")]
pub mod tui;
#[cfg(feature = "gui")]
pub mod ui;
pub mod wildcard;
pub mod workspace;
pub mod wrap_layout;
